import type { ProjectState } from '@ensemble/core';

export function particle(text: string, pair: '을/를' | '이/가' = '을/를'): string {
  const last = text.replace(/[\s"'”’)]/g, '').at(-1) ?? '';
  const code = last.charCodeAt(0) - 0xac00;
  const consonant = code >= 0 && code <= 11171 ? code % 28 !== 0 : /[013678lmn]$/i.test(last);
  return pair.split('/')[consonant ? 0 : 1]!;
}
export const taskName = (state: ProjectState, id: string) => state.tasks.get(id)?.spec.title ?? state.plan?.tasks.find(t => t.id === id)?.title ?? '작업';
const operations: Record<string, string> = { exclude_scope: '범위 제외', limit_scope: '범위 한정', set_availability: '가용 시간 변경', handoff_early: '초안 인계', reassign: '담당 변경', set_deadline: '기한 변경', change_goal: '목표 변경' };
/** Last boundary before channel output; internal references remain in ledger evidence. */
export function channelText(text: string, state: ProjectState, maxSentences = 2): string {
  let result = text.replace(/\b(?:result|msg|forecast|decision):[^\s,;"')]+/g, '기록');
  for (const [key, label] of Object.entries(operations)) result = result.replaceAll(key, label);
  for (const task of state.plan?.tasks ?? []) {
    const escaped = task.id.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    result = result.replace(new RegExp(`(?<![\\w-])${escaped}(?![\\w-])`, 'g'), task.title);
  }
  result = result.replace(/([^\s]+)을\(를\)/g, (_, word: string) => word + particle(word))
    .replace(/([^\s]+)이\(가\)/g, (_, word: string) => word + particle(word, '이/가'));
  return result.split(/(?<=[.!?])\s+/).slice(0, maxSentences).join(' ').trim();
}

/** Numeric surface forms are generated by code, including rounded values and date components. */
export function numericFacts(value: unknown): Set<string> {
  const values = new Set<string>();
  const visit = (v: unknown): void => {
    if (typeof v === 'number' && Number.isFinite(v)) {
      for (const n of [v, Math.round(v), Number(v.toFixed(1)), Number(v.toFixed(2))]) values.add(String(n));
    } else if (v instanceof Date) visit(v.toISOString());
    else if (typeof v === 'string') for (const n of v.match(/\d+(?:\.\d+)?/g) ?? []) values.add(String(Number(n)));
    else if (Array.isArray(v)) v.forEach(visit);
    else if (v && typeof v === 'object') Object.values(v).forEach(visit);
  };
  visit(value); return values;
}
export function hasGroundedNumbers(text: string, allowed: Set<string>): boolean {
  return (text.match(/\d+(?:\.\d+)?/g) ?? []).every(n => allowed.has(String(Number(n))));
}
