import { expect, it } from "vitest";
import { AUTOMATION_LIMIT, automationGate, isAutomationAction, limitReachedEvent, planStarts, project } from "../src/index.ts";
import type { LedgerEvent, NewLedgerEvent } from "../src/index.ts";
it("caps PM actions at twelve, emits one notice per projected interval, and resumes", () => {
  const ctx = { projectId: "p", targetProductId: "p" };
  const events: LedgerEvent[] = [];
  const append = (event: NewLedgerEvent) => events.push({ ...event, seq: events.length + 1, id: `${events.length}`, at: "fixed" });
  append({ ...ctx, actor: { kind: "human", id: "u" }, type: "plan_committed", payload: { version: 1, basedOn: null, tasks: ["A", "B"].map((id) => ({ id, title: id, assignee: "u", dependsOn: [], handoffConditions: [] })), reason: "plan", approvedBy: "u", sourceMessageIds: [] } });
  expect(limitReachedEvent(project(events), ctx)).toBeNull();
  for (let i = 0; i < AUTOMATION_LIMIT - 1; i++) append({ ...ctx, actor: { kind: "pm", id: "pm" }, type: "change_notified", payload: { changeId: `c${events.length}`, planVersion: 1, recipientId: "u", text: "changed", via: "next_turn" } });
  expect(automationGate(project(events))).toEqual({ allowed: true, remaining: 1 });
  const starts = planStarts(project(events), "go", ctx);
  expect(starts).toHaveLength(1);
  starts.forEach(append);
  expect(automationGate(project(events))).toEqual({ allowed: false, remaining: 0 });
  expect(planStarts(project(events), "go", ctx)).toEqual([]);
  const notice = limitReachedEvent(project(events), ctx)!;
  expect(limitReachedEvent(project(events), ctx)).toEqual(notice);
  append(notice);
  expect(project(events).automation).toEqual({ actionsSinceResume: 12, limitReached: true });
  expect(limitReachedEvent(project(events), ctx)).toBeNull();
  append({ ...ctx, actor: { kind: "pm", id: "pm" }, type: "automation_resumed", payload: { by: "u" } });
  expect(automationGate(project(events))).toEqual({ allowed: true, remaining: 12 });
  expect(planStarts(project(events), "go", ctx)).toHaveLength(1);
  for (let i = 0; i < AUTOMATION_LIMIT; i++) append({ ...ctx, actor: { kind: "pm", id: "pm" }, type: "change_notified", payload: { changeId: `c${events.length}`, planVersion: 1, recipientId: "u", text: "changed", via: "next_turn" } });
  expect(limitReachedEvent(project(events), ctx)?.idempotencyKey).not.toBe(notice.idempotencyKey);
});

it('twelve speeches, considerations and decision records do not consume the state-change budget', () => {
  const events: LedgerEvent[] = [];
  for (let i = 0; i < 12; i++) for (const type of ['pm_spoke', 'pm_considered', 'decision_recorded']) {
    events.push({ id: `${type}:${i}`, seq: events.length + 1, at: 'fixed', projectId: 'p', targetProductId: 'p', actor: { kind: 'pm', id: 'pm' }, type,
      payload: { messageId: `speech:${i}`, text: 'fact', considerationId: `${i}`, triggerId: `${i}`, openTopics: [], decisionId: `d:${i}`, sourceMessageIds: [], approvedBy: 'pm' } });
  }
  expect(automationGate(project(events))).toEqual({ allowed: true, remaining: 12 });
});

it.each(['plan_committed', 'task_start_reserved', 'update_sent', 'revision_requested', 'change_notified'])('counts automatic %s but not a human action', type => {
  expect(isAutomationAction({ type, actor: { kind: 'pm', id: 'pm' } })).toBe(true);
  expect(isAutomationAction({ type, actor: { kind: 'human', id: 'owner' } })).toBe(false);
});

it('counts change notifications generated by the system on behalf of the PM', () => {
  expect(isAutomationAction({ type: 'change_notified', actor: { kind: 'system', id: 'pm' } })).toBe(true);
  expect(isAutomationAction({ type: 'plan_committed', actor: { kind: 'system', id: 'seed' } })).toBe(false);
});

it.each(['conclusion', 'plan-card', 'authority-card'])('starts a new interval after an explicit human %s', kind => {
  const events: LedgerEvent[] = [];
  const append = (type: string, payload: unknown, actor = { kind: 'system' as const, id: 'pm' }) => events.push({ id: `${events.length}`, seq: events.length + 1, at: 'fixed', projectId: 'p', targetProductId: 'p', actor, type, payload });
  append('member_joined', { memberId: 'owner', kind: 'human' });
  append('member_joined', { memberId: 'designer', kind: 'human' });
  append('goal_set', { decider: 'owner' });
  for (let i = 0; i < 12; i++) append('change_notified', { changeId: `old:${i}`, recipientId: 'owner' });
  append('action_limit_reached', { count: 12, limit: 12 });
  append('message_recorded', { messageId: 'proposal', authorId: 'designer', text: 'proposal' });
  append('decision_recorded', { decisionId: 'proposal', sourceMessageIds: ['proposal'], approvedBy: 'pm' });
  expect(automationGate(project(events))).toEqual({ allowed: false, remaining: 0 });
  if (kind === 'conclusion') {
    append('message_recorded', { messageId: 'conclusion', authorId: 'owner', text: 'confirmed conclusion' });
    append('decision_recorded', { decisionId: 'confirmed', sourceMessageIds: ['conclusion'], approvedBy: 'pm' });
  } else if (kind === 'plan-card') {
    append('plan_proposed', { proposalId: 'card', forMemberId: 'owner' });
    append('plan_decided', { proposalId: 'card', memberId: 'owner', approved: false });
    expect(automationGate(project(events)).allowed).toBe(false);
    append('plan_proposed', { proposalId: 'approved-card', forMemberId: 'owner' });
    append('plan_decided', { proposalId: 'approved-card', memberId: 'owner', approved: true });
  } else {
    append('authority_requested', { requestId: 'card', personId: 'owner' });
    append('authority_granted', { requestId: 'card', personId: 'owner', granted: true });
  }
  expect(automationGate(project(events))).toEqual({ allowed: true, remaining: 12 });
  append('change_notified', { changeId: 'new', recipientId: 'owner' });
  // Replaying the same conclusion/approval cannot clear the new work's count.
  if (kind === 'conclusion') append('decision_recorded', { decisionId: 'repeated', sourceMessageIds: ['conclusion'], approvedBy: 'pm' });
  else if (kind === 'plan-card') append('plan_decided', { proposalId: 'approved-card', memberId: 'owner', approved: true });
  else append('authority_granted', { requestId: 'card', personId: 'owner', granted: true });
  expect(automationGate(project(events))).toEqual({ allowed: true, remaining: 11 });
});
