import { expect, it } from "vitest";
import { project, isStaleResult } from "../src/index.ts";
import type { EventPayloads, EventType, LedgerEvent, TaskSpec } from "../src/index.ts";
it("replays deterministically, preserves unchanged specs, resets changed checks, and cancels removed work", () => {
  const events: LedgerEvent[] = [];
  const emit = <K extends EventType>(type: K, payload: EventPayloads[K]) => events.push({ id: `${events.length}`, seq: events.length + 1, at: "fixed", projectId: "p", targetProductId: "p", actor: { kind: "human", id: "u" }, type, payload });
  const spec: TaskSpec = { id: "T", title: "Task", assignee: "u", dependsOn: [], handoffConditions: [] };
  const plan = (version: number, tasks: TaskSpec[]) => emit("plan_committed", { version, basedOn: version - 1, tasks, reason: "Plan", approvedBy: "u", sourceMessageIds: [] });
  plan(1, [spec]);
  emit("task_started", { taskId: "T" });
  emit("task_blocked", { taskId: "T", reason: "Waiting", unblockBy: "u" });
  emit("task_blocked", { taskId: "T", reason: "Still waiting" });
  expect(project(events).tasks.get("T")?.blocked?.prevStatus).toBe("running");
  emit("task_resumed", { taskId: "T" });
  expect(project(events).tasks.get("T")?.status).toBe("running");
  emit("result_submitted", { taskId: "T", resultId: "r", planVersion: 1, summary: "Done", artifactIds: [] });
  emit("task_checked", { taskId: "T", resultId: "r", reason: "Met" });
  plan(2, [spec]);
  expect(project(events).tasks.get("T")).toMatchObject({ status: "checked", specVersion: 1 });
  plan(3, [{ ...spec, title: "Changed" }]);
  const changed = project(events).tasks.get("T")!;
  expect(changed).toMatchObject({ status: "ready", specVersion: 3 });
  expect(changed.checkedResultId).toBeUndefined();
  expect(isStaleResult(changed, "r")).toBe(true);
  emit("availability_updated", { memberId: "u", weeklyHours: 20 });
  emit("estimate_updated", { taskId: "T", hours: { min: 1, max: 3 }, source: "human" });
  const a = project(events);
  expect(project(events)).toEqual(a);
  expect(a.availability.get("u")).toBe(20);
  expect(a.estimates.get("T")).toEqual({ min: 1, max: 3, source: "human" });
  a.tasks.get("T")!.spec.handoffConditions.push("mutated");
  expect(project(events).tasks.get("T")?.spec.handoffConditions).toEqual([]);
  plan(4, []);
  emit("task_started", { taskId: "T" });
  expect(project(events).tasks.get("T")?.status).toBe("cancelled");
  const unknown: LedgerEvent = { ...events[0]!, seq: 99, type: "message_recorded", payload: { text: "Hello" } };
  expect(project([...events, unknown])).toEqual({ ...project(events), lastSeq: 99 });
});
