import { expect, it } from "vitest";
import { project, isStaleResult, planStarts } from "../src/index.ts";
import type { EventPayloads, EventType, LedgerEvent, TaskSpec } from "../src/index.ts";
it("replays deterministically, preserves unchanged specs, resets changed checks, and cancels removed work", () => {
  const events: LedgerEvent[] = [];
  const emit = <K extends EventType>(type: K, payload: EventPayloads[K]) => events.push({ id: `${events.length}`, seq: events.length + 1, at: "fixed", projectId: "p", targetProductId: "p", actor: { kind: "human", id: "u" }, type, payload });
  const spec: TaskSpec = { id: "T", title: "Task", assignee: "u", dependsOn: [], handoffConditions: [] };
  const plan = (version: number, tasks: TaskSpec[]) => emit("plan_committed", { version, basedOn: version - 1, tasks, reason: "Plan", approvedBy: "u", sourceMessageIds: [] });
  plan(1, [spec]);
  emit("task_started", { taskId: "T" });
  emit("task_blocked", { taskId: "T", reason: "Waiting", unblockBy: "u" });
  emit("task_blocked", { taskId: "T", reason: "Still waiting" });
  expect(project(events).tasks.get("T")?.blocked?.prevStatus).toBe("running");
  emit("task_resumed", { taskId: "T" });
  expect(project(events).tasks.get("T")?.status).toBe("running");
  emit("result_submitted", { taskId: "T", resultId: "r", planVersion: 1, summary: "Done", artifactIds: [] });
  emit("task_checked", { taskId: "T", resultId: "r", reason: "Met" });
  plan(2, [spec]);
  expect(project(events).tasks.get("T")).toMatchObject({ status: "checked", specVersion: 1 });
  plan(3, [{ ...spec, title: "Changed" }]);
  const changed = project(events).tasks.get("T")!;
  expect(changed).toMatchObject({ status: "ready", specVersion: 3 });
  expect(changed.checkedResultId).toBeUndefined();
  expect(isStaleResult(changed, "r")).toBe(true);
  emit("availability_updated", { memberId: "u", weeklyHours: 20 });
  emit("estimate_updated", { taskId: "T", hours: { min: 1, max: 3 }, source: "human" });
  const a = project(events);
  expect(project(events)).toEqual(a);
  expect(a.availability.get("u")).toBe(20);
  expect(a.estimates.get("T")).toEqual({ min: 1, max: 3, source: "human" });
  a.tasks.get("T")!.spec.handoffConditions.push("mutated");
  expect(project(events).tasks.get("T")?.spec.handoffConditions).toEqual([]);
  plan(4, []);
  emit("task_started", { taskId: "T" });
  expect(project(events).tasks.get("T")?.status).toBe("cancelled");
  const unknown: LedgerEvent = { ...events[0]!, seq: 99, type: "message_recorded", payload: { text: "Hello" } };
  expect(project([...events, unknown])).toEqual({ ...project(events), lastSeq: 99 });
});

it('keeps a continuation turn occupied until it ends without reserving the task again', () => {
  const events: LedgerEvent[] = [];
  const context = { projectId: 'p', targetProductId: 'p' };
  const emit = <K extends EventType>(type: K, payload: EventPayloads[K]) => events.push({ ...context, id: `${events.length}`, seq: events.length + 1, at: 'fixed', actor: { kind: 'system', id: 'pm' }, type, payload });
  for (const memberId of ['agent', 'other']) emit('member_joined', { memberId, kind: 'agent', displayName: memberId });
  const tasks = ['a', 'b'].map(id => ({ id, title: id, assignee: 'agent', dependsOn: [], handoffConditions: [] }));
  emit('plan_committed', { version: 1, basedOn: null, tasks, reason: 'initial', approvedBy: 'owner', sourceMessageIds: [] });
  emit('task_start_reserved', { taskId: 'a', specVersion: 1, trigger: 'initial' });
  emit('task_started', { taskId: 'a', turnId: 'original' });
  emit('turn_observed', { agentId: 'agent', taskId: 'a', turnId: 'original', status: 'completed' });
  expect(project(events).activeTurn.size).toBe(0);
  emit('turn_observed', { agentId: 'other', taskId: 'a', turnId: 'wrong-owner', status: 'started' });
  emit('turn_observed', { agentId: 'agent', taskId: 'b', turnId: 'not-running', status: 'started' });
  expect(project(events).activeTurn.size).toBe(0);
  emit('turn_observed', { agentId: 'agent', taskId: 'a', turnId: 'continuation', status: 'started' });
  const running = project(events);
  expect(running.activeTurn.get('agent')).toBe('a');
  expect(planStarts(running, 'while-continuing', context)).toEqual([]);
  expect(running.reservedStartKeys).toEqual(new Set(['start:a:v1']));
  emit('turn_observed', { agentId: 'agent', taskId: 'a', turnId: 'continuation', status: 'completed' });
  expect(project(events).activeTurn.size).toBe(0);
  expect(planStarts(project(events), 'after-continuing', context).map(e => (e.payload as { taskId: string }).taskId)).toEqual(['b']);
});
